### ISSUE TITLE
"All" als vorausgewählte Option

### ISSUE THREAD

**Issue by Ahobert** [Ahobert/dash-oauni-oase#10]
https://github.com/Ahobert/dash-oauni-oase/blob/22f16ee6702a03e692cbb5bd4e9e3f28c5c9bc54/International-Academic-Mobility/country_gender_field.Rmd#L30

Hier ist beim Laden "Physical sciences" vorausgewählt. Kann man das ändern zu "All" (bei den anderen Tabellen ist meiner Erinnerung nach "All" als erstes).

**Comment by momenifi** [comment]
Erledigt
