### ISSUE TITLE
size figures mobility flow

### ISSUE THREAD

**Issue by Ahobert** [Ahobert/dash-oauni-oase#2]
The size of the three individual figures in the mobility flow part is very small. It is hard to see anything. Maybe we could show the three plots one above the other instead of next to each other? 

https://github.com/Ahobert/dash-oauni-oase/blob/789f6033d4610842be02433b3f0614f1f67135d8/International-Academic-Mobility/mobility_flow.Rmd#L61

**Comment by momenifi** [comment]
I tried to put them in different rows, but it was not an observable change. Now I made the diagram higher and think it is better. Please check whether it makes sense now.

Von: Ahobert ***@***.***>
Gesendet: Mittwoch, 31. August 2022 17:33
An: Ahobert/dash-oauni-oase ***@***.***>
Cc: Momeni, Fakhri ***@***.***>; Assign ***@***.***>
Betreff: [Ahobert/dash-oauni-oase] size figures mobility flow (Issue #2)


The size of the three individual figures in the mobility flow part is very small. It is hard to see anything. Maybe we could show the three plots one above the other instead of next to each other?

https://github.com/Ahobert/dash-oauni-oase/blob/789f6033d4610842be02433b3f0614f1f67135d8/International-Academic-Mobility/mobility_flow.Rmd#L61

**Comment by Ahobert** [comment]
Unfortunately, I can not seem to make it well visible. I played around a bit with figure height and width and also with text size in the .R file. I think the problem is, that the figure width also affects the fontsize of the labels. I always just see the labels or nothing at all. Maybe we could change the labels to L, LM, UM, U and explain in the text what they mean? Or remove them and add labels at the very right and left of the whole plot, not for each single plot individually?

**Comment by momenifi** [comment]
Look at this one please!

**Comment by Ahobert** [comment]
Thanks for your efforts. I still cannot seem to make it work. If I am right, there is no interactivity for this plot, is there? Maybe we can try to include a fixed image instead. As a first step in that direction, can you maybe add your precompiled html file to the repo again, and I will try to use that instead of the Rmd file.
![Screenshot 2022-09-01 at 14-24-03 OASE_OAUNI Dashboard - Mobility flows](https://user-images.githubusercontent.com/44192428/187920768-e09c1854-ce1b-4e4f-87e3-a9e02e058c71.png)

**Comment by momenifi** [comment]
It is of course not good. I see something else from html file.

**Comment by momenifi** [comment]
![image](https://user-images.githubusercontent.com/11192908/187923624-aac09136-ac4d-4e19-ba68-223c21eceb2a.png)

**Comment by Ahobert** [comment]
That does look better. Unfortunately, I can not include html files as subsites. A work around might be to create an image file (png for example or a vector graphic) and have a Rmd file where we just include the image. Still, it is puzzling that it does not work with the framework and navigation added. I managed by now to have the plot visible, but even if I enlarge the size, the resulting plots will not get bigger than in the image attached. I was wondering if maybe somehow there is some padding added around the single plots that prevents them from extending to the whole width of the lines below?
![Screenshot 2022-09-02 at 11-45-38 OASE_OAUNI Dashboard - Mobility flows!](https://user-images.githubusercontent.com/44192428/188113246-eb4c0281-9b58-4756-b5ac-19eb156ad720.png)

**Comment by Ahobert** [comment]
Actually, maybe it has got something to do with my browser (Firefox on ubuntu), because your html file look like this when I open it:
![Screenshot 2022-09-02 at 11-51-52 Mobility flows!](https://user-images.githubusercontent.com/44192428/188114120-5002148f-01b2-4751-9fb3-74a041f1af08.png)

**Comment by momenifi** [comment]
I think the problem is combineWidgets i used in the Rmd file. I changed the code a little. Changing the width in this combineWidgets could solve the problem.

**Comment by Ahobert** [comment]
This works better now. I actually think, it also might have something to do with my browser (Firefox) because when I open your html file I also seem to have this kind of box around the single figures (see image), which are therefore scaled to appear smaller than the width of the lines below would allow. There is still room for improvement, but I would leave it for now and focus on getting things online with Github actions. Maybe it appears correct there and if not we can try again then.
![Screenshot 2022-09-02 at 11-51-52 Mobility flows!](https://user-images.githubusercontent.com/44192428/188418542-78f3842d-8d79-4907-bf20-1ee446244269.png)
