### ISSUE TITLE
add descriptive text for tables and figures

### ISSUE THREAD

**Issue by Ahobert** [Ahobert/dash-oauni-oase#3]
Für manche Unterseiten habe ich bereits Texte hinzugefügt, die auf den google docs basieren. Diese müssten gegengelesen und ggf. angepasst werden. Für andere fehlt erläuternder Text noch vollständig, dieser müsste ergänzt werden. Auch titles und subtitles müssten geprüft werden. Diese habe ich geändert damit das, was in title steht, in die Navigationsleiste passt.

Gegenlesen:
[ ] alle .Rmd Dateien aus dem Mobility Ordner
[ ] mobility.qmd
[ ] oa_nature.qmd (hier müsste auch die Übersichtstabelle mit allen Merkmalen noch eingefügt werden

Texte einfügen:
[ ] alle .Rmd Dateien aus dem OA-Nature Ordner

**Comment by momenifi** [comment]
Übersichtstabelle in oa_nature.qmd?

**Comment by Ahobert** [comment]
Im google doc zu diesem Paper ist als erstes eine Tabelle mit den erhobenen Variablen. Ist das relevant hier? Im Text wird darauf verwiesen.

**Comment by momenifi** [comment]
Die Tabelle ist schon drin: 'Mobility per field and gender'

**Comment by Ahobert** [comment]
Und auch hier noch ein paar kleinere Anmerkungen:
Im mobility-flow Dokument ist bei der Bildunterschrift auch eine kurze Interpretation (The highest mobility flow happens ...) https://github.com/Ahobert/dash-oauni-oase/blob/22f16ee6702a03e692cbb5bd4e9e3f28c5c9bc54/International-Academic-Mobility/mobility_flow.Rmd#L78
So eine kurze Erläuterung, was genau der Plot aussagt, wäre meiner Ansicht nach auch noch schön bei der Grafik zum Mobility score (https://github.com/Ahobert/dash-oauni-oase/blob/22f16ee6702a03e692cbb5bd4e9e3f28c5c9bc54/International-Academic-Mobility/mobility_score_distribution.Rmd#L81) und Centrality measures (https://github.com/Ahobert/dash-oauni-oase/blob/22f16ee6702a03e692cbb5bd4e9e3f28c5c9bc54/International-Academic-Mobility/centrality.Rmd#L67).

Bei mobility score wäre noch gut zu erwähnen, wie der berechnet wird (vermutlich Anzahl von Ortswechseln?).

Bei den centrality measures bräuchten wir noch Erklärungen, was die einzelnen Maße genau sind oder aber zumindest Links zu Seiten, die das erklären, zB Wikipedia oder so.

Bei der Citation analysis (OA Nature) fehlt noch ein Satz dazu, was highly cited bedeutet (mehr als x Zitationen oder im x-ten Perzentil innerhalb des Fachgebiets oder...?) https://github.com/Ahobert/dash-oauni-oase/blob/22f16ee6702a03e692cbb5bd4e9e3f28c5c9bc54/Springer_Nature-Open_Access/citation.Rmd#L26

**Comment by momenifi** [comment]
Done.
