### ISSUE TITLE
add citations 

### ISSUE THREAD

**Issue by Ahobert** [Ahobert/dash-oauni-oase#7]
add citations of preprints and publications to pubs.qmd file

add links to pecific papers to individual overview pages (General Info) of the resp. papers

**Comment by momenifi** [comment]
what do you mean by adding citations?

**Comment by Ahobert** [comment]
just what you did, add relevant papers in the pubs.qmd file and links to papers in the overview page of that article. Do you want to mention other OASE papers in the qmd file? Where we don't make interactive plots, but just to advertise also other works related to OASE / OAUNI projects?

**Comment by Ahobert** [comment]
@PhilippMayr , was denkst du?
