### ISSUE TITLE
Spaltenüberschriften und Achsenbeschriftungen überarbeiten

### ISSUE THREAD

**Issue by Ahobert** [Ahobert/dash-oauni-oase#9]

**Comment by momenifi** [comment]
Ich habe es in viele Stellen gemacht. Bitte guck mal ob es jetzt ok ist.

**Comment by Ahobert** [comment]
Viel besser so. Ein paar  Kleinigkeiten sind mir noch aufgefallen:
- das g von corresponding landet in der nächsten Zeile in zwei Tabellen. Vielleicht kannst du die Spalten ein kleines bisschen breiter machen, sodass es passt? https://github.com/Ahobert/dash-oauni-oase/blob/cc397be46e8516d4548194767db13acc61a3c4d2/Springer_Nature-Open_Access/model_income.Rmd#L61 https://github.com/Ahobert/dash-oauni-oase/blob/cc397be46e8516d4548194767db13acc61a3c4d2/Springer_Nature-Open_Access/hybrid_model_income.Rmd#L55
- beim Barplot steht nicht, was die 5 Balken bedeuten: https://github.com/Ahobert/dash-oauni-oase/blob/cc397be46e8516d4548194767db13acc61a3c4d2/Springer_Nature-Open_Access/journals_model.Rmd#L51
- Die einzelnen Plots überlappen und die Zahlen der x Achse gucken unter den Überschriften der unteren Plots hervor: https://github.com/Ahobert/dash-oauni-oase/blob/cc397be46e8516d4548194767db13acc61a3c4d2/International-Academic-Mobility/centrality.Rmd#L36
